; Note: this is a Input = Output mapping.
; Updated to 1.20.1 item names (The Flattening)
;
;---
; OVERWORLD ITEMS
;---
; Wood
" U |   |   " U:ic2:uu_matter = minecraft:oak_log*8
; Stone
"   | U |   " U:ic2:uu_matter = minecraft:stone*16
; Stone Bricks
"UU |UU |U  " U:ic2:uu_matter = minecraft:chiseled_stone_bricks*48
; Grass
"   |U  |U  " U:ic2:uu_matter = minecraft:grass_block*16
; Mycelium
"   |U U|UUU" U:ic2:uu_matter = minecraft:mycelium*24
; Mossy Cobblestone
"   | U |U U" U:ic2:uu_matter = minecraft:mossy_cobblestone*16
; Clay
"UU |U  |UU " U:ic2:uu_matter = minecraft:clay_ball*48
; Flint
" U |UU |UU " U:ic2:uu_matter = minecraft:flint*32
; Glass
" U |U U| U " U:ic2:uu_matter = minecraft:glass*32
; Wool
"U U|   | U " U:ic2:uu_matter = minecraft:white_wool*12

; DESERT ITEMS
;---
; Sandstone
"   |  U| U " U:ic2:uu_matter = minecraft:sandstone*16
; Cactus
" U |UUU|U U" U:ic2:uu_matter = minecraft:green_dye*48

; ICY ITEMS
;---
; Snow
"U U|   |   " U:ic2:uu_matter = minecraft:snow_block*16
; Snowball
"   |   |UUU" U:ic2:uu_matter = minecraft:snowball*16

; PLANT LIFE
;---
; Cocoa Beans
"UU |  U|UU " U:ic2:uu_matter = minecraft:cocoa_beans*32
; Lily Pads
"U U| U | U " U:ic2:uu_matter = minecraft:lily_pad*64
; Sugar Cane
"U U|U U|U U" U:ic2:uu_matter = minecraft:sugar_cane*48
; Sticky Resin
"U U|   |U U" U:ic2:uu_matter = ic2:resin*21
; Vines
"U  |U  |U  " U:ic2:uu_matter = minecraft:vine*24

; LIQUIDS
;---
; Water
"   | U | U " U:ic2:uu_matter = ic2:water_sheet
; Lava
" U | U | U " U:ic2:uu_matter = ic2:lava_sheet

; NETHER ITEMS
;---
; Obsidian
"U U|U U|   " U:ic2:uu_matter = minecraft:obsidian*12
; Netherrack
"  U| U |U  " U:ic2:uu_matter = minecraft:netherrack*16
; Glowstone
" U |U U|UUU" U:ic2:uu_matter = minecraft:glowstone_dust*8

; MOB DROPS
;---
; Gunpower
"UUU|U  |UUU" U:ic2:uu_matter = minecraft:gunpowder*15
; Bone
"U  |UU |U  " U:ic2:uu_matter = minecraft:bone*32
; Feather
" U | U |U U" U:ic2:uu_matter = minecraft:feather*32
; Ink Sac
" UU| UU| U " U:ic2:uu_matter = minecraft:ink_sac*48
; Ender Pearl
"UUU|U U| U " U:ic2:uu_matter = minecraft:ender_pearl

; ORES
;---
; Coal
"  U|U  |  U" U:ic2:uu_matter = minecraft:coal*20
; Copper Dust
"  U|U U|   " U:ic2:uu_matter = ic2:copper_dust*10
; Tin Dust
"   |U U|  U" U:ic2:uu_matter = ic2:tin_dust*10
; Iron Dust
"U U| U |U U" U:ic2:uu_matter = ic2:iron_dust*4
; Lead Dust
"UUU|UUU|U  " U:ic2:uu_matter = ic2:lead_dust*14
; Gold Dust
" U |UUU| U " U:ic2:uu_matter = ic2:gold_dust*4
; Lapis Lazuli
" U | U | UU" U:ic2:uu_matter = minecraft:lapis_lazuli*9
; Redstone
"   | U |UUU" U:ic2:uu_matter = minecraft:redstone*24
; Diamond
"UUU|UUU|UUU" U:ic2:uu_matter = minecraft:diamond
; Emerald Ore
"UU |U U| UU" U:ic2:uu_matter = minecraft:emerald_ore
; Emerald
"UUU|UUU| U " U:ic2:uu_matter = minecraft:emerald*2
